In [147]:
# Q1
import numpy as np 
import scipy 
# a
n = 10 
main_diag = -2* np.ones(n)
upper_diag = 1* np.ones(n-2)
lower_diag = 3* np.ones(n-4)
A = np.diag(main_diag, 0) + np.diag(upper_diag, 2) + np.diag(lower_diag, -4)
#b
[p,L,U] = scipy.linalg.lu(A, p_indices=True)

b = np.array([20, 18, 16, 14, 12, 10, 8, 6, 4, 2])

# solving Ly = Pb
y = scipy.linalg.solve(L, b[p])

# solving Ux = y 
x = scipy.linalg.solve(U, y)

# residual vector
r = A @ x - b

r1norm = scipy.linalg.norm(r, 1)

print(A)

[[-2.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -2.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -2.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -2.  0.  1.  0.  0.  0.  0.]
 [ 3.  0.  0.  0. -2.  0.  1.  0.  0.  0.]
 [ 0.  3.  0.  0.  0. -2.  0.  1.  0.  0.]
 [ 0.  0.  3.  0.  0.  0. -2.  0.  1.  0.]
 [ 0.  0.  0.  3.  0.  0.  0. -2.  0.  1.]
 [ 0.  0.  0.  0.  3.  0.  0.  0. -2.  0.]
 [ 0.  0.  0.  0.  0.  3.  0.  0.  0. -2.]]
