# Question 5

In [20]:
import numpy as np 
import scipy
N = 4
h = 1/N
x = []
for index in range(0, N+1):
    x_n = index*h
    x.append(x_n)
print(x)

[0.0, 0.25, 0.5, 0.75, 1.0]


In [159]:
# define 
row = 0
a = []
A = np.zeros((N,N))
A[row, 0] += 3
A[row, 1] += -4
A[row, 2] += 1 
a.append(0)
f = lambda x: (np.pi**2 /4 + 1) * np.cos(np.pi + np.pi*(x/2))
row = 1
for i in range(1, N):
    try:
        if i + 1 == 4:
            A[row, i] += -2 - h**2 
            A[row, i -1] += 1
        else:
            A[row, i] += -2 - h**2 
            A[row, i+1] += 1
            A[row, i -1] += 1
            
        a_val = h**2 * f(x[i])
        a.append(a_val)
        row += 1
    except IndexError as e:
        print(f"oh no {e}")
        print(A)

print(A)
print(a)
    

[[ 3.     -4.      1.      0.    ]
 [ 1.     -2.0625  1.      0.    ]
 [ 0.      1.     -2.0625  1.    ]
 [ 0.      0.      1.     -2.0625]]
[0, -0.20021630672179566, -0.15323892694351673, -0.08293230965241935]


In [163]:
norm = np.linalg.norm(A.T @ A - np.identity(N), 2)
norm

32.96717919759065

## whats types of matrix is A?
### is it orthogonal, symetric, svd?
(1) A.T /= A -> not symetric -> no chol
(2) Orthgonal -> since the norm > 0 clearly not orthogonal 
(3) LU factorisation !


In [169]:
U4 = scipy.linalg.solve(A, a)
print(U4)

[0.99101639 0.91964721 0.70553968 0.38228945]


In [173]:
g = lambda x: np.cos(np.pi*x / 2)
u = [] 
u.append(U4[0])
for index in range(0,N-1):
    u_val = g(x[index])
    u.append(u_val)
print(u)
print(U4)


[0.9910163920694773, 1.0, 0.9238795325112867, 0.7071067811865476]
[0.99101639 0.91964721 0.70553968 0.38228945]


In [173]:
g = lambda x: np.cos(np.pi*x / 2)
u = [] 
u.append(U4[0])
for index in range(0,N-1):
    u_val = g(x[index])
    u.append(u_val)
print(u)
print(U4)


[0.9910163920694773, 1.0, 0.9238795325112867, 0.7071067811865476]
[0.99101639 0.91964721 0.70553968 0.38228945]


In [ ]:
U4=solve(A,a)
E=zeros(3)
OC=zeros(2)
for i in range(0,3):
    N=(2**i)*80
    x1 = linspace(0,1,N+1);
    U = zeros(N)
    h1=1/N
    d1=ones(N‐1)
    d4=ones(N‐1)
    d1[0]=‐4
    d2=zeros(N‐2)
    d2[0]=1
    d3=ones(N)*(‐2‐h1**2)
    d3[0]=3 A1=diag(d1,1)+diag(d4,‐1)+diag(d3)+diag(d2,2) a1=zeros(N) a1[1:]=h1**2*(1+pi**2/4)*cos(pi+pi/2*x1[1:N]) U=solve(A1,a1)
    u= cos(pi/2*x1[0:N]).T
    E[i]=norm(U‐u,inf)