# Boundary value problems

In [7]:
import numpy as np 
import scipy
from numpy import ndarray
from scipy.sparse import csc_array
from scipy.linalg import lu
from scipy.sparse.linalg import splu

A = np.array([[1,0,2], [1,3,0], [2,3,0]])
spA = csc_array(A)
print(spA)
print(A)

  (0, 0)	1
  (1, 0)	1
  (2, 0)	2
  (1, 1)	3
  (2, 1)	3
  (0, 2)	2
[[1 0 2]
 [1 3 0]
 [2 3 0]]
